### ISSUE TITLE
Default hub alias breaks zsh completion

### ISSUE THREAD

**Issue by mikemcquaid** [boxen/puppet-hub#5]
Please excuse me if I've just been stupid here but it seems the default hub alias breaks zsh's git completion. When I remove it then the git completion starts magically working again.

Thanks for your great work here!

(Paging @dgoodlad.)

**Comment by brodock** [comment]
This looks not to be fixed, please see:

https://github.com/robbyrussell/oh-my-zsh/issues/766

**Comment by mislav** [comment]
OK let me reopen while I investigate.

**Comment by mislav** [comment]
There are known issues with our zsh completion, some of which might be related to this one: https://github.com/github/hub/issues?q=is%3Aissue+is%3Aopen+zsh

@brodock Which oh-my-zsh plugins do you have loaded?

**Comment by brodock** [comment]
@mislav plugins=(git git-extras git-remote-branch postgres rails ruby brew bundler zeus)

**Comment by mikemcquaid** [comment]
@mislav Did you get any more insight here?

**Comment by mislav** [comment]
No, it's something I still need to look at within the hub repo. It doesn't have anything to do with puppet-hub, though. There are enough open issues in hub repo about this, so there's no reason to keep this open.

**Comment by mikemcquaid** [comment]
Cool, thanks!
